CREATE TABLE s_system (app_name text primary key, app_value text);
CREATE TABLE [m_user] ([id] integer PRIMARY KEY NOT NULL, [name] text NOT NULL, [create_date] datetime NOT NULL, [update_date] datetime NOT NULL, [delete_flg] tinyint NOT NULL);
CREATE TABLE [m_payment] ([id] integer PRIMARY KEY NOT NULL, [name] text NOT NULL, [create_date] datetime NOT NULL, [update_date] datetime NOT NULL, [delete_flg] tinyint NOT NULL);
CREATE TABLE [m_major] ([id] integer PRIMARY KEY NOT NULL, [name] text NOT NULL, [type] tinyint NOT NULL, [sort] integer NOT NULL, [create_date] datetime NOT NULL, [update_date] datetime NOT NULL, [delete_flg] tinyint NOT NULL);
CREATE TABLE [m_sub] ([id] integer PRIMARY KEY NOT NULL, [major_id] integer NOT NULL, [name] text NOT NULL, [optimal] GMoney NOT NULL, [range] GMoney NOT NULL, [sort] integer NOT NULL, [create_date] datetime NOT NULL, [update_date] datetime NOT NULL, [delete_flg] tinyint NOT NULL);
CREATE TABLE [d_bill] ([id] integer PRIMARY KEY NOT NULL, [bill_date] varchar(10) NOT NULL, [user_id] integer NOT NULL, [sub_id] integer NOT NULL, [payment_id] integer NOT NULL, [annual_budget] tinyint NOT NULL, [amount] GMoney NOT NULL, [remarks] text, [fixed_id] integer, [create_date] datetime NOT NULL, [update_date] datetime NOT NULL);
CREATE TABLE [d_fixed_data] ([id] integer PRIMARY KEY NOT NULL, [user_id] integer NOT NULL, [sub_id] integer NOT NULL, [interval_type] tinyint NOT NULL, [interval] tinyint NOT NULL, [detail] text, [amount] GMoney NOT NULL, [remarks] text, [start_date] datetime NOT NULL, [end_date] datetime NOT NULL, [create_date] datetime NOT NULL, [update_date] datetime NOT NULL);
CREATE TABLE [d_budget] ([id] integer PRIMARY KEY  NOT NULL ,[year] varchar(4), [category_id] integer NOT NULL,[category_type] tinyint NOT NULL,[amount] GMoney NOT NULL, [create_date] datetime NOT NULL, [update_date] datetime NOT NULL);


CREATE VIEW v_sub as select major.id as major_id, major.name as major_name, major.type as bill_type, major.sort as major_sort, sub.id as sub_id, sub.name as sub_name, sub.id as ID, sub.name as Name, Optimal, Range, sub.sort as sub_sort from m_sub as sub left outer join m_major as major on sub.major_id = major.id and major.delete_flg = 0 where sub.delete_flg = 0;
CREATE VIEW v_fixed_data as select fixed.id as id, fixed.user_id as user_id, user.name as user_name, fixed.sub_id as sub_id, sub.name as sub_name, sub.bill_type as bill_type, sub.major_sort as major_sort, sub.sub_sort as sub_sort, fixed.interval_type as interval_type, fixed.interval as interval, fixed.detail as detail, fixed.amount as amount, fixed.remarks as remarks, fixed.start_date as start_date, fixed.end_date as end_date from d_fixed_data as fixed left outer join m_user as user on fixed.user_id = user.id left outer join v_sub as sub on fixed.sub_id = sub.id ;
CREATE VIEW v_bill as select bill.id, bill_date, bill.user_id as user_id, user.name as user_name, major.id as major_id, major.name as major_name, major.type as bill_type, major.sort as major_sort, sub_id, sub.name as sub_name, sub.sort as sub_sort, sub.name as Name, payment_id, pay.name as payment_name, annual_budget, amount, remarks,fixed_id, bill.create_date, bill.update_date from d_bill as bill left outer join m_user as user on user_id = user.id left outer join m_sub as sub on sub_id = sub.id left outer join m_major as major on sub.major_id = major.id left outer join m_payment as pay on payment_id = pay.id;

insert into s_system values ('login_password', null);
insert into s_system values ('last_vacuum_date', null);

insert into m_major values (NULL,'Housing',0,1, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Food',0,2, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Cost of utilities',0,3, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Communication cost',0,4, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Transportation',0,5, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Education',0,6, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Recreational',0,7, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Acquaintanceship',0,8, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Beauty & Clothing',0,9, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Healthcare cost',0,10, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Investment',0,11, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Other',0,99, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Insurance',2,901, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Social Insurance',2,902, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Taxes',2,903, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Salary Income',1,951, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Investment Income',1,952, datetime('now'), datetime('now'), 0);
insert into m_major values (NULL,'Other Income',1,953, datetime('now'), datetime('now'), 0);

insert into m_sub values (0, 0,'Expense', 280000, 30000, 0, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,1,'Rent',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,1,'Groceries & Ornaments',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,1,'Furniture & Electronics',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,1,'Household services',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,1,'Homeowner''s Dues',0,0,5, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,1,'Waste disposal fee',0,0,6, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,1,'Repair cost',0,0,7, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,1,'Other',0,0,8, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,2,'Food',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,2,'Dinning out',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,2,'School meal fees',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,2,'Other',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,3,'Natural Gas/Oil',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,3,'Water & Sewer',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,3,'Other',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,3,'Electric bill',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,4,'Television',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,4,'Telephone & Mobile',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,4,'Shipping charges',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,4,'Postcards, stamps & etc.',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,4,'Internet',0,0,5, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,5,'Train pass',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,5,'Gasoline',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,5,'Car maintenance costs',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,5,'Parking fee',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,5,'Other',0,0,5, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,6,'Books & Magazines',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,6,'Tuition',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,6,'School & Training',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,1,'Childcare fee',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,7,'Movie & Concert',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,7,'Recreational supplies',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,7,'Toys',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,7,'Enrichment lessons',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,7,'Trip',0,0,5, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,7,'Lottery',0,0,6, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,8,'Ceremonial fees',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,8,'Donation',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,8,'Expense Accounts/Membership',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,8,'Gift',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,8,'Other',0,0,5, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,9,'Clothing',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,9,'Cleaning',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,9,'Beauty & Barber',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,10,'Drug',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,10,'Medical apparatus',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,10,'Hospital',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,10,'Other',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,11,'Stockholders',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,11,'Other',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,12,'Allowance',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,12,'Incidentals',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,12,'Remittance',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,12,'Miscellaneous',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,13,'Personal pension',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,13,'Corporate pension',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,13,'Car insurance',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,13,'Life insurance',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,13,'Property and casualty insurance',0,0,5, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,14,'Health insurance',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,14,'Employment insurance',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,14,'Employment Pension',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,14,'National Pension',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,15,'Withholding tax',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,15,'Fixed asset tax and city planning tax',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,15,'Car tax',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,15,'Resident tax',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,15,'Other',0,0,5, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,16,'Part-time job or sideline income',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,16,'Salaries and wages',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,16,'Overtime pay',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,16,'Other allowances',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,16,'Severance pay',0,0,5, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,16,'Bonus',0,0,6, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,16,'Extraordinary revenue',0,0,7, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,17,'Dividend',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,17,'Trading profit and loss',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,17,'Contribution',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,18,'Health insurance benefits',0,0,1, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,18,'Bounty',0,0,2, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,18,'Lotteries',0,0,3, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,18,'Public pension benefits',0,0,4, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,18,'Life insurance and private pension',0,0,5, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,18,'Unemployment insurance benefits',0,0,6, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,18,'Child allowance',0,0,7, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,18,'From beneficiary',0,0,8, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,18,'Income tax refunds',0,0,9, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,18,'Stock option',0,0,10, datetime('now'), datetime('now'), 0);
insert into m_sub values (NULL,18,'Other',0,0,11, datetime('now'), datetime('now'), 0);

insert into m_payment values (NULL, 'Cash', datetime('now'), datetime('now'), 0);
insert into m_payment values (NULL, 'Credit', datetime('now'), datetime('now'), 0);
insert into m_payment values (NULL, 'Bank', datetime('now'), datetime('now'), 0);

insert into m_user values (0, 'Family', datetime('now'), datetime('now'), 0);