//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMoney.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMoney.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Add_16 {
            get {
                object obj = ResourceManager.GetObject("Add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_32 {
            get {
                object obj = ResourceManager.GetObject("Add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_user_32 {
            get {
                object obj = ResourceManager.GetObject("add_user_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Back_Button_32 {
            get {
                object obj = ResourceManager.GetObject("Back_Button_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calendar_16 {
            get {
                object obj = ResourceManager.GetObject("Calendar_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calendar_32 {
            get {
                object obj = ResourceManager.GetObject("Calendar_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Expense Share\r\n(Total : {0}).
        /// </summary>
        internal static string ChartTabPieTitle {
            get {
                return ResourceManager.GetString("ChartTabPieTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Collapse_16 {
            get {
                object obj = ResourceManager.GetObject("Collapse_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE s_system (app_name text primary key, app_value text);
        ///CREATE TABLE [m_user] ([id] integer PRIMARY KEY NOT NULL, [name] text NOT NULL, [create_date] datetime NOT NULL, [update_date] datetime NOT NULL, [delete_flg] tinyint NOT NULL);
        ///CREATE TABLE [m_payment] ([id] integer PRIMARY KEY NOT NULL, [name] text NOT NULL, [create_date] datetime NOT NULL, [update_date] datetime NOT NULL, [delete_flg] tinyint NOT NULL);
        ///CREATE TABLE [m_major] ([id] integer PRIMARY KEY NOT NULL, [name] text NOT NULL, [t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Database_16 {
            get {
                object obj = ResourceManager.GetObject("Database_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete_16 {
            get {
                object obj = ResourceManager.GetObject("Delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_16 {
            get {
                object obj = ResourceManager.GetObject("Edit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Exit_16 {
            get {
                object obj = ResourceManager.GetObject("Exit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Expand_16 {
            get {
                object obj = ResourceManager.GetObject("Expand_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Forward_Button_32 {
            get {
                object obj = ResourceManager.GetObject("Forward_Button_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gnome_Edit_Clear_32 {
            get {
                object obj = ResourceManager.GetObject("Gnome_Edit_Clear_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Budget : {0}.
        /// </summary>
        internal static string GroupBoxAnnualBudgetTitle {
            get {
                return ResourceManager.GetString("GroupBoxAnnualBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance : {0}.
        /// </summary>
        internal static string GroupBoxBalanceTitle {
            get {
                return ResourceManager.GetString("GroupBoxBalanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense : {0} .
        /// </summary>
        internal static string GroupBoxExpenseTitle {
            get {
                return ResourceManager.GetString("GroupBoxExpenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income : {0} .
        /// </summary>
        internal static string GroupBoxIncomeTitle {
            get {
                return ResourceManager.GetString("GroupBoxIncomeTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Info_32 {
            get {
                object obj = ResourceManager.GetObject("Info_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string LabelAmount {
            get {
                return ResourceManager.GetString("LabelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Budget.
        /// </summary>
        internal static string LabelAnnualBudget {
            get {
                return ResourceManager.GetString("LabelAnnualBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance with Annual Budget: {0}.
        /// </summary>
        internal static string LabelBalanceWithAnnual {
            get {
                return ResourceManager.GetString("LabelBalanceWithAnnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance without Annual Budget : {0}.
        /// </summary>
        internal static string LabelBalanceWithoutAnnual {
            get {
                return ResourceManager.GetString("LabelBalanceWithoutAnnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string LabelGeneral {
            get {
                return ResourceManager.GetString("LabelGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string LabelMonth {
            get {
                return ResourceManager.GetString("LabelMonth", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Merge_16 {
            get {
                object obj = ResourceManager.GetObject("Merge_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Backup Successfully!.
        /// </summary>
        internal static string MSG_BACKUP_OK {
            get {
                return ResourceManager.GetString("MSG_BACKUP_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected items ?.
        /// </summary>
        internal static string MSG_DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should select only one item to edit..
        /// </summary>
        internal static string MSG_EDIT {
            get {
                return ResourceManager.GetString("MSG_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MSG_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Name you add is already exist!.
        /// </summary>
        internal static string MSG_EXIST_USER {
            get {
                return ResourceManager.GetString("MSG_EXIST_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] has already started!.
        /// </summary>
        internal static string MSG_INI_0001 {
            get {
                return ResourceManager.GetString("MSG_INI_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It failed in initialization..
        /// </summary>
        internal static string MSG_INI_0002 {
            get {
                return ResourceManager.GetString("MSG_INI_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should select more than one item to merge..
        /// </summary>
        internal static string MSG_MERGE {
            get {
                return ResourceManager.GetString("MSG_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge selected items ?.
        /// </summary>
        internal static string MSG_MERGE_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_MERGE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should select items with same user and remarks in the same category..
        /// </summary>
        internal static string MSG_MERGE_INVALID {
            get {
                return ResourceManager.GetString("MSG_MERGE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password invalid!.
        /// </summary>
        internal static string MSG_OPT_0001 {
            get {
                return ResourceManager.GetString("MSG_OPT_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password doesn&apos;t match!.
        /// </summary>
        internal static string MSG_OPT_0002 {
            get {
                return ResourceManager.GetString("MSG_OPT_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The StartDate should smaller than EndDate !.
        /// </summary>
        internal static string MSG_OPT_0003 {
            get {
                return ResourceManager.GetString("MSG_OPT_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Password Invalid! Try again..
        /// </summary>
        internal static string MSG_PWD_INVALID {
            get {
                return ResourceManager.GetString("MSG_PWD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Item!.
        /// </summary>
        internal static string MSG_SELECT {
            get {
                return ResourceManager.GetString("MSG_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MSG_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum successfully!.
        /// </summary>
        internal static string MSG_VACUUM {
            get {
                return ResourceManager.GetString("MSG_VACUUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t do Vacuum for a month.\r\nDo it Now ?.
        /// </summary>
        internal static string MSG_VACUUM_CHECK {
            get {
                return ResourceManager.GetString("MSG_VACUUM_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MSG_WARNING {
            get {
                return ResourceManager.GetString("MSG_WARNING", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Secure_32 {
            get {
                object obj = ResourceManager.GetObject("Secure_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} of {1} items, Total : {2}.
        /// </summary>
        internal static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} of {1} items, Total : {2}, Average : {3}.
        /// </summary>
        internal static string StatusLabelWithAverage {
            get {
                return ResourceManager.GetString("StatusLabelWithAverage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Tick_16 {
            get {
                object obj = ResourceManager.GetObject("Tick_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tools_16 {
            get {
                object obj = ResourceManager.GetObject("Tools_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
